### PR TITLE
Fix build (wrong sha256)

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
@Suzie97 the package won't build beause of vala. Previously it had the wrong checksum, so the latest update never happened on flathub

**Comment by hfiguiere** [comment]
You merged a broken PR

**Comment by Suzie97** [comment]
> You merged a broken PR

aahhh. I thought you added the correct checksum, and the app should build now. I just released a new version of the app, if I update the manifest file with the new release checksum, will that work?

**Comment by hfiguiere** [comment]
the failure was a vala failure.

**Comment by hfiguiere** [comment]
so it depends, it can't be worse.

**Comment by Suzie97** [comment]
@hfiguiere is there anything I can do to fix this issue?

**Comment by hfiguiere** [comment]
fixing the code? you are upstream it's your responsibility.

**Comment by Suzie97** [comment]
> fixing the code? you are upstream it's your responsibility.

sorry for bothering you, but I don't really understand the vala problem here.

**Comment by SubhadeepJasu** [comment]
Making a build to view the build log in order to troubleshoot the issue.

bot, build com.github.suzie97.communique

**Comment by SubhadeepJasu** [comment]
@Suzie97 Does it build locally?

**Pull request merged**
